repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

environments:
  local:
    values:
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl

releases:
  - name: ingress-nginx
    labels:
      app: ingress-nginx
    wait: true
    chart: ingress-nginx/ingress-nginx
    version: 4.10.1
    values:
      - values-ingress-nginx.yaml.gotmpl

  - name: to-dos-api
    labels:
      app: to-dos-api
    wait: true
    chart: bitnami/nginx
    # after 15.3.5 our docker file or setup can no longer start, need to investigate what is wrong for the newer versions
    version: 15.3.5
    # it won't work anyway until ingress controller is created
    # thus we wait for it to be ready first
    needs: 
      - ingress-nginx
    values:
      # https://helmfile.readthedocs.io/en/latest/#loading-remote-environment-values-files
      - git::https://github.com/TourmalineCore/to-dos-api.git@/ci/values.yaml?ref=feature/docker
      - values.yaml.gotmpl

  - name: to-dos-ui
    labels:
      app: to-dos-ui
    wait: true
    chart: bitnami/nginx
    # after 15.3.5 our docker file or setup can no longer start, need to investigate what is wrong for the newer versions
    version: 15.3.5
    # it won't work anyway until ingress controller is created
    # thus we wait for it to be ready first
    needs: 
      - ingress-nginx
      - to-dos-api
    values:
      # https://helmfile.readthedocs.io/en/latest/#loading-remote-environment-values-files
      - git::https://github.com/TourmalineCore/to-dos-ui.git@/ci/values.yaml?ref=feature/docker
      - values.yaml.gotmpl
      - values-to-dos-ui.yaml.gotmpl
